[tool.bumpver]
current_version = "0.4.0"
version_pattern = 'MAJOR.MINOR.PATCH[PYTAGNUM]'
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true


[tool.bumpver.file_patterns]
"bumpver.toml" = ['current_version = "{version}"']
"gui.py" = ['__version__ = "{version}"']
'pyproject.toml' =['version = "{version}"']